### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by jonathanicq** [miouzikal/hassio-addons#8]
HI @miouzikal 

I've set the robot but getting this feedback from Binance API

binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
2021-05-29 12:11:59,042 - crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/strategies/hassio_default_strategy.py", line 23, in scout
    super().scout()
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/strategies/default_strategy.py", line 34, in scout
    self._jump_to_best_coin(current_coin, current_coin_price, all_tickers)
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/auto_trader.py", line 140, in _jump_to_best_coin
    ratio_dict = self._get_ratios(coin, coin_price, all_tickers)
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/auto_trader.py", line 127, in _get_ratios
    transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/binance_api_manager.py", line 62, in get_fee
    bnb_balance = self.get_currency_balance("BNB")
  File "/addons/binance-trade-bot-for-hassio/app/binance_trade_bot/binance_api_manager.py", line 92, in get_currency_balance
    for currency_balance in self.binance_client.get_account()["balances"]:
  File "/usr/lib/python3.8/site-packages/binance/client.py", line 1822, in get_account
    return self._get('account', True, data=params)
  File "/usr/lib/python3.8/site-packages/binance/client.py", line 292, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/lib/python3.8/site-packages/binance/client.py", line 242, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/lib/python3.8/site-packages/binance/client.py", line 237, in _request
    return self._handle_response()
  File "/usr/lib/python3.8/site-packages/binance/client.py", line 285, in _handle_response
    raise BinanceAPIException(self.response)
    
    Is that linked to the amout of coins ? is there anything that I should do ?

**Comment by miouzikal** [comment]
You can join the discord and search for this error message. It's likely due to the amount of coins and/or the SCOUT_SLEEP_TIME.
Not an error of the addon itself.
You can either set your SCOUT_SLEEP_TIME to something like 30 seconds or use a different branch which supports websockets.

**Comment by jonathanicq** [comment]
@miouzikal 
I guess was linked to the amout of coins.
So I've reduced them and it's running without errors.

Thank you
